courses = [
  [ "3D grafikus rendszerek", "BMEVIIIAC01" ],
  [ "Adatvezérelt alkalmazások fejlesztése", "BMEVIAUA369" ],
  [ "Adatvezérelt rendszerek", "BMEVIAUAC01" ],
  [ "Alkalmazásfejlesztési környezetek", "BMEVIAUAC04" ],
  [ "Informatikai rendszertervezés", "BMEVIMIAC01" ],
  [ "Integrációs és ellenőrzési technikák", "BMEVIMIAC04" ],
  [ "Intelligens rendszerfelügyelet", "BMEVIMIA370" ],
  [ "Kliensoldali technológiák", "BMEVIAUAC02" ],
  [ "Kooperatív és tanuló rendszerek", "BMEVIMIA357" ],
  [ "Mobil infokommunikációs rendszerek", "BMEVIHIA317" ],
  [ "Objektumorientált szoftvertervezés", "BMEVIIIAC00" ],
  [ "Objektumorientált szoftvertervezés", "BMEVIIIA371" ]
]

courses.each do |name, neptun|
  Course.create( name: name, neptun: neptun )
end

instructors = [
  [ "Ács Judit", "N3P7UN", false, false, false ],
  [ "Albert István", "N3P7UN", false, false, false ],
  [ "Asztalos Márk", "N3P7UN", false, true, false ],
  [ "Benedek Zoltán", "N3P7UN", false, false, false ],
  [ "Blázovics László", "N3P7UN", false, true, false ],
  [ "Braun Patrik János", "N3P7UN", false, false, true ],
  [ "Budai Ádám", "N3P7UN", false, false, true ],
  [ "Charaf Hassan", "N3P7UN", true, false, false ],
  [ "Cserkúti Péter", "N3P7UN", false, false, false ],
  [ "Csorba Kristóf", "N3P7UN", false, true, false ],
  [ "Dudás Ákos", "N3P7UN", false, true, false ],
  [ "Dunaev Dmitriy", "N3P7UN", false, false, false ],
  [ "Ekler Péter", "N3P7UN", false, true, false ],
  [ "Fekete Tamás", "N3P7UN", false, false, true ],
  [ "Forstner Bertalan", "N3P7UN", true, false, false ],
  [ "Lengyel László", "N3P7UN", true, false, false ],
  [ "Gazdi László", "N3P7UN", false, false, true ],
  [ "Hideg Attila", "N3P7UN", false, false, true ],
  [ "Imre Gábor", "N3P7UN", false, false, false ],
  [ "Iváncsy Szabolcs", "N3P7UN", false, true, false ],
  [ "Jánoky László Viktor", "N3P7UN", false, false, true ],
  [ "Kovács Tibor", "N3P7UN", false, true, false ],
  [ "Kővári Bence András", "N3P7UN", false, true, false ],
  [ "Kövesdán Gábor", "N3P7UN", false, false, false ],
  [ "Kundra László János", "N3P7UN", false, false, false ],
  [ "Vajk István", "N3P7UN", true, false, false ],
  [ "Mezei Gergely", "N3P7UN", false, true, false ],
  [ "Pomázi Krisztián", "N3P7UN", false, false, true ],
  [ "Rajacsics Tamás", "N3P7UN", false, false, false ],
  [ "Recski Gábor András", "N3P7UN", false, true, false ],
  [ "Simon Gábor", "N3P7UN", false, false, false ],
  [ "Sipos Márton Ákos", "N3P7UN", false, false, false ],
  [ "Somogyi Ferenc Attila", "N3P7UN", false, false, true ],
  [ "Szabó Gábor", "N3P7UN", false, false, false ],
  [ "Tóth Tibor", "N3P7UN", false, false, false ],
  [ "Tömösközi Máté Ferenc", "N3P7UN", false, false, true ],
  [ "Szécsi László", "N3P7UN", false, false, false ],
  [ "Gincsai Gábor", "N3P7UN", false, false, false ],
  [ "Bányász Gábor", "N3P7UN", false, false, false ],
  [ "Filep Szabolcs", "N3P7UN", false, false, false ],
  [ "Micskei Zoltán Imre", "N3P7UN", false, false, false ],
  [ "Strausz György", "N3P7UN", false, false, false ],
  [ "Horváth Gábor", "N3P7UN", false, false, false ],
  [ "Goldschmidt Balázs", "N3P7UN", false, false, false ],
  [ "Hamar János Krisztián", "N3P7UN", false, false, false ],
  [ "Kökényesi Tamás", "N3P7UN", false, false, false ],
  [ "Kis-Nagy Dániel Dávid", "N3P7UN", false, false, false ],
  [ "Fazekas Péter", "N3P7UN", false, false, false ]
]

#in this seed the instructors are made with randomised neptun codes
instructors.each do |name, neptun, can_be_president, can_be_member, can_be_secretary|
  Instructor.create( name: name,
  	             neptun: ("a".."z").to_a.concat( (0..9).to_a ).shuffle[0..5].join.upcase,
  	             can_be_president: can_be_president,
  	             can_be_secretary: can_be_secretary,
  	             can_be_member: can_be_member )
end

students = [
  [ "Andrási Bulcsú János", "ZEZFCE", "Rajacsics Tamás", "BMEVIIIAC01" ],
  [ "Antal Gábor", "FC3E51", "Ekler Péter", "BMEVIAUA369" ],
  [ "Arnócz László", "PV8AK9", "Blázovics László", "BMEVIAUAC01" ],
  [ "Beckl Gábor", "WX7TPZ", "Gincsai Gábor", "BMEVIAUA369" ],
  [ "Berta Balázs", "BB6JQY", "Tóth Tibor", "BMEVIAUAC02" ],
  [ "Bihary Gergely Sándor", "DJY1FZ", "Ekler Péter", "BMEVIAUAC02" ],
  [ "Blum Márton", "N104LU", "Forstner Bertalan", "BMEVIAUA369" ],
  [ "Bodor Norbert", "CA25RQ", "Kővári Bence András", "BMEVIAUAC02" ],
  [ "Bognár Márton József", "OES1HB", "Blázovics László", "BMEVIAUAC01" ],
  [ "Braun Márton Szabolcs", "YJ8F2X", "Ekler Péter", "BMEVIAUAC01" ],
  [ "Burján Viktor", "MLTYU6", "Ács Judit", "BMEVIAUAC04" ],
  [ "Czap Balázs", "KUKYQ2", "Forstner Bertalan", "BMEVIAUAC02" ],
  [ "Csányi Marcell Péter", "FP9W6B", "Tóth Tibor", "BMEVIAUAC04" ],
  [ "Cserna Balázs", "MFIAU4", "Ács Judit", "BMEVIIIAC00" ],
  [ "Csőre Antal Tamás", "AR9EI8", "Dunaev Dmitriy", "BMEVIAUA369" ],
  [ "Dávid Ádám", "AO4S5C", "Ekler Péter", "BMEVIAUAC02" ],
  [ "Déri Tamás", "BAMRHY", "Szabó Gábor", "BMEVIAUAC02" ],
  [ "Elek Dávid István", "SI69U0", "Forstner Bertalan", "BMEVIMIA370" ],
  [ "Élő Dénes Bence", "LA7VEL", "Kővári Bence András", "BMEVIMIAC01" ],
  [ "Erdős Szilvia", "AE6QQJ", "Kővári Bence András", "BMEVIAUAC02" ],
  [ "Falvai Olivér Benjámin", "M1Y8AJ", "Forstner Bertalan", "BMEVIAUAC02" ],
  [ "Farkas Gergő", "EOW3AB", "Kővári Bence András", "BMEVIAUA369" ],
  [ "Fodor Gábor Dániel", "FQ0Y7K", "Forstner Bertalan", "BMEVIAUAC02" ],
  [ "Gáspár Vilmos", "GF4UZL", "Benedek Zoltán", "BMEVIAUAC01" ],
  [ "Gyárfás Gábor", "YOMPPI", "Tóth Tibor", "BMEVIAUAC02" ],
  [ "György Tímea", "FIAFO1", "Dudás Ákos", "BMEVIAUAC01" ],
  [ "Győri Mihály", "PFGIXS", "Csorba Kristóf", "BMEVIAUA369" ],
  [ "Horváth Péter", "VSRVMZ", "Rajacsics Tamás", "BMEVIAUA369" ],
  [ "Huszti Dorottya", "F9MLB3", "Ács Judit", "BMEVIAUAC02" ],
  [ "Jáhn Erik", "AF1WZU", "Fekete Tamás", "BMEVIAUAC01" ],
  [ "Jancsovics Tamás", "DDIY6U", "Ekler Péter", "BMEVIHIA317" ],
  [ "Jenei Máté", "G1CH4I", "Benedek Zoltán", "BMEVIAUAC02" ],
  [ "Jóna Kata", "IP1LXW", "Ekler Péter", "BMEVIAUAC01" ],
  [ "Kálmán Bence", "B06FMG", "Kővári Bence András", "BMEVIAUAC01" ],
  [ "Karancsi Ádám", "G1W3OD", "Kővári Bence András", "BMEVIAUA369" ],
  [ "Károlyi Áron", "FXXNGR", "Kővári Bence András", "BMEVIAUA369" ],
  [ "Kiss Szabolcs", "FGCUAP", "Tóth Tibor", "BMEVIAUAC02" ],
  [ "Koleszár Patrik", "TLCXYA", "Kővári Bence András", "BMEVIAUAC01" ],
  [ "Kovács Bálint István", "WP3OGO", "Ekler Péter", "BMEVIAUAC01" ],
  [ "Kovács Benedek", "HLWG0Q", "Blázovics László", "BMEVIIIAC00" ],
  [ "Kovács Dániel", "E0UTKP", "Szabó Gábor", "BMEVIAUAC01" ],
  [ "Kovács Tibor", "IS8IJS", "Simon Gábor", "BMEVIAUAC01" ],
  [ "Kővári Balázs", "TV071O", "Benedek Zoltán", "BMEVIAUA369" ],
  [ "Kristály Márk", "DTJ4Z0", "Ekler Péter", "BMEVIAUA369" ],
  [ "Kulacs Péter", "G5IJFF", "Gincsai Gábor", "BMEVIAUAC02" ],
  [ "Kutasy Kitti", "OVUMC2", "Csorba Kristóf", "BMEVIAUAC04" ],
  [ "Lohonyai Bálint", "JAB2F8", "Dudás Ákos", "BMEVIAUA369" ],
  [ "Magyar Gábor István", "VNQ45A", "Lengyel László", "BMEVIIIAC00" ],
  [ "Mentler Dávid", "E03FHG", "Kövesdán Gábor", "BMEVIIIAC00" ],
  [ "Mihályi Balázs", "LU8D88", "Kővári Bence András", "BMEVIAUAC02" ],
  [ "Móczár Dávid", "AGVNXV", "Simon Gábor", "BMEVIAUAC01" ],
  [ "Müller Gergő Bence", "GDL0HB", "Forstner Bertalan", "BMEVIAUAC01" ],
  [ "Nagy Bence Zsigmond", "A9PACJ", "Ekler Péter", "BMEVIAUAC02" ],
  [ "Nagy Nikolett", "CF70RC", "Ács Judit", "BMEVIAUAC02" ],
  [ "Nagy Péter Géza", "G2R7EV", "Ács Judit", "BMEVIAUAC02" ],
  [ "Nagy Péter Szabolcs", "ACD6T6", "Forstner Bertalan", "BMEVIAUAC02" ],
  [ "Németh Gergely Dániel", "C44ZM7", "Ács Judit", "BMEVIMIAC01" ],
  [ "Palatinszky Dániel Gábor", "DMEM3S", "Mezei Gergely", "BMEVIAUAC02" ],
  [ "Páli Márton", "Z2PWV9", "Tóth Tibor", "BMEVIAUAC02" ],
  [ "Pap Edina", "XD9T9V", "Hideg Attila", "BMEVIAUAC04" ],
  [ "Pápai Attila", "X6YVJM", "Szabó Gábor", "BMEVIIIA371" ],
  [ "Paróczi Gergő", "O4ZDQ5", "Hamar János Krisztián", "BMEVIAUAC04" ],
  [ "Perneky Virág", "VZX4GR", "Kis-Nagy Dániel Dávid", "BMEVIAUA369" ],
  [ "Pintér Benedek", "WO892L", "Kővári Bence András", "BMEVIAUAC02" ],
  [ "Princz Ákos", "A3BC1G", "Simon Gábor", "BMEVIIIAC00" ],
  [ "Rostás Balázs", "C00P7Q", "Forstner Bertalan", "BMEVIAUAC02" ],
  [ "Rottenhoffer Olivér", "M9TEFT", "Imre Gábor", "BMEVIAUAC02" ],
  [ "Stoica Márk", "MPG13R", "Sipos Márton Ákos", "BMEVIAUAC02" ],
  [ "Sümegi Márk", "DVIFYV", "Kökényesi Tamás", "BMEVIMIAC04" ],
  [ "Szabó András Gábor", "MWQCI9", "Forstner Bertalan", "BMEVIAUAC01" ],
  [ "Szabó Attila Dániel", "U76H5P", "Ács Judit", "BMEVIAUAC02" ],
  [ "Szabó Dóra", "KFK3T0", "Gincsai Gábor", "BMEVIAUAC02" ],
  [ "Szabo Zsombor-Tamás", "MWT0KX", "Asztalos Márk", "BMEVIAUA369" ],
  [ "Szántó Dávid Gergely", "Y7L145", "Albert István", "BMEVIAUAC02" ],
  [ "Szemán Bence", "PT9H3E", "Imre Gábor", "BMEVIAUAC04" ],
  [ "Szendi Tamás Pál", "XEENOE", "Gincsai Gábor", "BMEVIAUA369" ],
  [ "Szigeti Blanka", "V8DGCO", "Csorba Kristóf", "BMEVIAUAC04" ],
  [ "Szilágyi Norbert Renátó", "AXFXRO", "Csorba Kristóf", "BMEVIAUAC01" ],
  [ "Szlovák Máté Ákos", "AG1UQU", "Blázovics László", "BMEVIAUA369" ],
  [ "Szücs Cintia Lia", "BOZQAN", "Kővári Bence András", "BMEVIAUAC02" ],
  [ "Takács Gergő", "E7FCHF", "Gazdi László", "BMEVIAUAC04" ],
  [ "Takács Levente", "PY82C7", "Hideg Attila", "BMEVIAUAC01" ],
  [ "Takács Norbert", "BR2LE6", "Forstner Bertalan", "BMEVIAUAC02" ],
  [ "Tautz Szilveszter", "AFGC8N", "Tóth Tibor", "BMEVIAUAC04" ],
  [ "Temesvári Fanni", "EIZUOZ", "Kővári Bence András", "BMEVIAUAC02" ],
  [ "Tolnay Zoltán", "CT65G8", "Mezei Gergely", "BMEVIAUA369" ],
  [ "Tombor Dániel", "RJ3KRA", "Forstner Bertalan", "BMEVIMIA357" ],
  [ "Tóth Attila", "X25EZO", "Szabó Gábor", "BMEVIAUAC02" ],
  [ "Tóth Dániel", "BCDP1Q", "Albert István", "BMEVIAUA369" ],
  [ "Tóth Péter István", "YS93EK", "Ekler Péter", "BMEVIAUAC01" ],
  [ "Tömpe Boldizsár", "AOVD7E", "Forstner Bertalan", "BMEVIAUAC01" ],
  [ "Ujhelyi Benedek", "BC4HFJ", "Blázovics László", "BMEVIAUAC02" ],
  [ "Varga Péter Krisztián", "HIXBYZ", "Dudás Ákos", "BMEVIAUA369" ],
  [ "Végh Éva", "JN12LH", "Imre Gábor", "BMEVIIIAC00" ],
  [ "Velez Krisztián", "WFPTP9", "Ekler Péter", "BMEVIAUAC01" ],
  [ "Veszner Dávid", "U8UH4E", "Blázovics László", "BMEVIAUA369" ],
  [ "Zaymus Gábor Mihály", "DDUU2Y", "Benedek Zoltán", "BMEVIAUAC02" ],
  [ "Zóka Dániel", "Y7G3ZL", "Kövesdán Gábor", "BMEVIAUAC01Zollai András" ],
  [ "Zollai András", "A5X7OI", "Cserkúti Péter", "BMEVIAUAC02" ],
  [ "Zöld Máté", "GQH7FW", "Fekete Tamás", "BMEVIAUAC01" ]
]

students.each do |name, neptun, supervisor, course_neptun|
  Student.create( name: name,
  	              neptun: neptun,
  	              supervisor_neptun: instructors.find(|i| i[0] == supervisor).second,
  	              course_neptun: course_neptun )
end
